name: lab07-project

services:

  web:
    build: .
    container_name: lab07-web
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lab07-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: lab07db
      MYSQL_USER: lab07user
      MYSQL_PASSWORD: lab07pass
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lab07-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root123
    depends_on:
      - db

volumes:
  db-data: